### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by cossatot** [cossatot/ssrd_pecube#13]
OK, since we're getting fairly close to lift-off, and you're also getting fairly close to getting the f out of the office for a while, we need to make a detailed task checklist that we can update progressively, so we know where we are with things.
### Richard's tasks:
- [ ] finish Python run job scripts:
  - these are called by a Bash script
    1. [x] modifies input files
    2. [ ] parses and saves results: 
       - copies Comparison.txt to persistent output directory
       - parses Comparison.txt and adds the variables and model results (modeled ages) to master dataframe
- [x] finish Bash script that helps these processes
  1. makes temp dir, copies files/dirs
  2. runs Python script that modifies input files
  3. runs Pecube
  4. copies Comparison.txt to persistent directory
  5. runs Python script that parses Comparison.txt and adds results to master dataframe
- [x] write modify_topo_parameters function in pecube_tools.py
- [ ] modify pt.read_comparison() to generate long 1D series for each run
- [x] make dataframe for generating run parameters (variables, etc.)
  1. [x] write code
  2. [x] update w/ new WPF constraints
- [ ] write Python script that submits jobs for the first batch
- [ ] preliminary analysis of preliminary results
  - update analysis scripts 
    - Bayesian inversion?
    - easier time series analysis
  - _obviously results need to exist_
### Sarah's tasks
- [x] make sure all software is installed on cluster (head node):
  1. [x] Python (anaconda/miniconda)
  2. [x] update conda (`conda update conda`)
  3. [x] ipython (`conda install ipython`)
  4. [x] numpy (`conda install numpy`)
  5. [x] pandas (`conda install pandas`)
- [ ] copy `scripts` folder from github to `~eqsarah/src/Pecube/scripts`
  - _have to wait until I finish it!_
- [ ] make sure correct input files are used
  - topo_parameters
  - fault_parameters
  - _soon they will be finished..._
- [ ] run test files
  - run make_combos.py for test batch
  - _again, once I'm finished_
- [ ] run first batch
